# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Category.create(:category_name => '文学・評論')
Category.create(:category_name => '人文・思想')
Category.create(:category_name => '社会・政治･法律')
Category.create(:category_name => 'ノンフィクション')
Category.create(:category_name => '歴史・地理')
Category.create(:category_name => 'ビジネス・経済')
Category.create(:category_name => '投資・金融・会社経営')
Category.create(:category_name => '科学・テクノロジー')
Category.create(:category_name => '医学・薬学・看護学・歯科学')
Category.create(:category_name => 'コンピュータ・IT')
Category.create(:category_name => 'アート・建築・デザイン')
Category.create(:category_name => '趣味・実用')
Category.create(:category_name => 'スポーツ・アウトドア')
Category.create(:category_name => '資格・検定・就職')
Category.create(:category_name => '暮らし・健康・子育て')
Category.create(:category_name => '旅行ガイド・マップ')
Category.create(:category_name => '語学・辞事典・年鑑')
Category.create(:category_name => '英語学習')
Category.create(:category_name => '教育・学参・受験')
Category.create(:category_name => '絵本・児童書')
Category.create(:category_name => 'コミック・ラノベ・BL')
Category.create(:category_name => 'ライトノベル')
Category.create(:category_name => 'タレント写真集')
Category.create(:category_name => 'ゲーム攻略本')
Category.create(:category_name => 'エンターテイメント')
Category.create(:category_name => '新書・文庫・ノベルス')
Category.create(:category_name => '雑誌')
Category.create(:category_name => '楽譜・スコア・音楽書')
Category.create(:category_name => 'カレンダー・手帳')
Category.create(:category_name => 'ポスター')
Category.create(:category_name => '古本')
Category.create(:category_name => '古書･希少本')
Category.create(:category_name => 'アダルト')